### Home Work #2 (100 marks)
**Due on March 14**  
Group Members Names

1)
2)

**1) Indexing (20 marks)**
1) read GDP data from "https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv"
2) rename the appropriate column to "GDP"
3) have data only for 2 countries of your choice and from 2020 onwards only using booliean filtering
5) set both country and year as index for the original datafram (not the selection ones)
6) repeat 3 using exactly for 2020 and 2023
7) repeat 3 but for 3 countries of your choice and from 2020 to 2023 (range). Hint use pd.IndexSlice

In [2]:
#part 1
import pandas as pd
gdp = pd.read_csv("https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv")
print(gdp.head())
#this involves reading a csv format file from a github site on the GDP of various countries using a pandas method pd.read_csv
#the print(gdp.head()) helps us see the first five rows of the gdp dataset.

  Country Name Country Code  Year         Value
0  Afghanistan          AFG  2000  3.521418e+09
1  Afghanistan          AFG  2001  2.813572e+09
2  Afghanistan          AFG  2002  3.825701e+09
3  Afghanistan          AFG  2003  4.520947e+09
4  Afghanistan          AFG  2004  5.224897e+09

In [9]:
#part 2
gdp
gdp = gdp.rename(columns = {"Value":"GDP"}) 
gdp
#this involves using the rename method to change the column name from "Value" to "Column" in the gdp dataset

      Country Name Country Code  Year           GDP
0      Afghanistan          AFG  2000  3.521418e+09
1      Afghanistan          AFG  2001  2.813572e+09
2      Afghanistan          AFG  2002  3.825701e+09
3      Afghanistan          AFG  2003  4.520947e+09
4      Afghanistan          AFG  2004  5.224897e+09
...            ...          ...   ...           ...
13974     Zimbabwe          ZWE  2019  2.183223e+10
13975     Zimbabwe          ZWE  2020  2.150970e+10
13976     Zimbabwe          ZWE  2021  2.837124e+10
13977     Zimbabwe          ZWE  2022  2.736663e+10
13978     Zimbabwe          ZWE  2023  2.653827e+10

[13979 rows x 4 columns]

In [15]:
#part 3
gdp
part3gdp = gdp[(gdp["Country Name"].isin(["Canada","Australia"])) & (gdp["Year"] >= 2020)]
partbgdp
#this involves using a boolean type filtering for obtaining data for Canada and Australia only, from 2020 onwards.
# the ... (gdp["Country Name"].isin(["Canada","Australia"])) & (gdp["Year"] >= 2020)
    # this will return true or false for every value if it meets the two conditions:
        # country name having Canada or Australia
        # year being 2020 or greater
#the & sign makes sure that both conditions are met for the output to be true.

     Country Name Country Code  Year           GDP
639     Australia          AUS  2020  1.330382e+12
640     Australia          AUS  2021  1.559034e+12
641     Australia          AUS  2022  1.692957e+12
642     Australia          AUS  2023  1.723827e+12
1972       Canada          CAN  2020  1.655685e+12
1973       Canada          CAN  2021  2.007472e+12
1974       Canada          CAN  2022  2.161483e+12
1975       Canada          CAN  2023  2.140086e+12

In [16]:
#part 4
part4gdp = gdp.set_index(["Country Name", "Year"])
part4gdp
#this involves setting multiple indexes to the original gdp data using the set_index method
#the result of the code also creates a hierarchal index:
    #with Country Name being in position 1, whereas Year being in position 2

                  Country Code           GDP
Country Name Year
Afghanistan  2000          AFG  3.521418e+09
             2001          AFG  2.813572e+09
             2002          AFG  3.825701e+09
             2003          AFG  4.520947e+09
             2004          AFG  5.224897e+09
...                        ...           ...
Zimbabwe     2019          ZWE  2.183223e+10
             2020          ZWE  2.150970e+10
             2021          ZWE  2.837124e+10
             2022          ZWE  2.736663e+10
             2023          ZWE  2.653827e+10

[13979 rows x 2 columns]

In [45]:
#part 5
part5gdp = part4gdp.loc[(["Australia","Canada"], [2020,2023]),:]
part5gdp
# Since we have to use filtering similar to part 3, 
    #we would now have to use the .loc method instead of using boolean filtering 
    #as the .isin method used in part 3 wouldn't work here, due to the columns being indexed.
# since we want specific countries and years
    #we can use the .isin method to obtain the rows that contain those specific values

                  Country Code           GDP
Country Name Year
Australia    2020          AUS  1.330382e+12
             2023          AUS  1.723827e+12
Canada       2020          CAN  1.655685e+12
             2023          CAN  2.140086e+12

In [42]:
#part 6
import pandas as pd
part6gdp = part4gdp.loc[pd.IndexSlice[["Australia","Canada","India"], 2020:2023], :]

#since question provides hint to use pd.IndexSlice, assuming have to use multi-indexed data from part 4
#this involves using IndexSlice for multi-index filtering.

                  Country Code           GDP
Country Name Year
Australia    2020          AUS  1.330382e+12
             2021          AUS  1.559034e+12
             2022          AUS  1.692957e+12
             2023          AUS  1.723827e+12
Canada       2020          CAN  1.655685e+12
             2021          CAN  2.007472e+12
             2022          CAN  2.161483e+12
             2023          CAN  2.140086e+12
India        2020          IND  2.674852e+12
             2021          IND  3.167271e+12
             2022          IND  3.353470e+12
             2023          IND  3.549919e+12

In [37]:
gdp.dtypes

Country Name     object
Country Code     object
Year              int64
GDP             float64
dtype: object

***2) Cleaning Data and Groupby (20 marks)***

1. Read titanic data from https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
2. Check the number of missing values for the columns
3. Fill missing Age values with median age and Fill missing Embarked with the most frequent port (note need to use mode()[0] as mode() -
4. Returns a series) and drop cabin column
5. Calculate average age of passengers by Pclass (1st, 2nd, 3rd class) and round to 2 decimal points
6. Calculate survival rate by Sex

In [ ]:
url_t = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titan = pd.read_csv(url_t)
titan.head()

***3) Seaborn Plot (20 marks)***

1) download `tips` data from seaborn
2) Draw a plot with spliting the data based on `time` and `smoking status`. Use `sex` for color and `size` for size
3) For the above `titanic data`, plot a histogram of `Age` for survived vs not survived passengers (use `hue`). Also add `kde` (kernal density estimate) or probability density. you may stack the two histograms.

In [112]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
# Load Seaboen's built-in example dataset
tips = sns.load_dataset("tips")
tips.head()

**4) Merge (20 marks)**
1) read GDP data from "https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv"
2) read population data from "https://raw.githubusercontent.com/datasets/population/master/data/population.csv"
3) Change "Year" from both data to numeric value.
4) Rename the columns as appropriate.
5) Have population data only for 2020 onwards
6) inner merge these two data with apprpriate common ids

***5) Time Series (20 marks)***

1) install yfinance (pip install yfinance) and then import
2) download the data as: df = yf.download("AAPL", start="2021-01-01", end="2023-12-31")
3) use df_aapl['Close'].plot() to plot time series. Give a suitable title and ylabel
4) plot 7 day and 30 day moving averages of `close` value and plot. Add title, xlabel, ylabel and legend

In [ ]:
import yfinance as yf

# Download Apple stock data from 2021-01-01 to 2023-12-31
df_aapl = yf.download("AAPL", start="2021-01-01", end="2023-12-31")
print(df_aapl.head())